# Generated by Django 6.0.4 on 2026-05-08 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squad_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coached_squads', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SquadPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batting_order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_captain', models.BooleanField(default=False)),
                ('is_wicketkeeper', models.BooleanField(default=False)),
                ('is_substitute', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad_memberships', to=settings.AUTH_USER_MODEL)),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='my_app.squad')),
            ],
            options={
                'ordering': ['batting_order'],
                'constraints': [models.UniqueConstraint(fields=('squad', 'player'), name='unique_player_per_squad'), models.UniqueConstraint(condition=models.Q(('is_substitute', False)), fields=('squad', 'batting_order'), name='unique_batting_order_per_squad')],
            },
        ),
    ]
