# Generated by Django 6.0.4 on 2026-05-08 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('win_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_former_player', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Player Role',
                'verbose_name_plural': 'Player Roles',
            },
        ),
        migrations.AlterField(
            model_name='squad',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coached_squads', to='my_app.coach'),
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stats', serialize=False, to='my_app.player')),
                ('runs_scored', models.IntegerField(default=0)),
                ('batting_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('strike_rate_bat', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('wickets_taken', models.IntegerField(default=0)),
                ('bowling_economy', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='squadplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad_memberships', to='my_app.player'),
        ),
        migrations.AddField(
            model_name='player',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='my_app.playerrole'),
        ),
    ]
