# Generated by Django 6.0.4 on 2026-06-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_coach_player_playerrole_alter_squad_coach_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixtureCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=120, unique=True)),
                ('data', models.JSONField()),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fixture Cache',
                'verbose_name_plural': 'Fixture Cache',
            },
        ),
        migrations.CreateModel(
            name='LiveScoreCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=120, unique=True)),
                ('data', models.JSONField()),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Live Score Cache',
                'verbose_name_plural': 'Live Score Cache',
            },
        ),
        migrations.CreateModel(
            name='PlayerStatsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=120, unique=True)),
                ('data', models.JSONField()),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Player Stats Cache',
                'verbose_name_plural': 'Player Stats Cache',
            },
        ),
    ]
