# Generated by Django 6.0.4 on 2026-06-17 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_fixturecache_livescorecache_playerstatscache'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='cricapi_id',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
