# Generated by Django 6.0.4 on 2026-06-17 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_player_cricapi_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_offset', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Player Sync State',
                'verbose_name_plural': 'Player Sync State',
            },
        ),
    ]
