# Generated by Django 6.0.4 on 2026-06-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_playersyncstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='overall_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
