# Generated by Django 6.0.4 on 2026-06-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_playerstats_overall_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='squadplayer',
            name='bowling_order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='squadplayer',
            constraint=models.UniqueConstraint(condition=models.Q(('is_substitute', False)), fields=('squad', 'bowling_order'), name='unique_bowling_order_per_squad'),
        ),
    ]
