# Generated by Django 6.0.4 on 2026-06-18 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_squadplayer_bowling_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='assistant_coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_coached_squads', to='my_app.coach'),
        ),
    ]
