# Generated by Django 6.0.4 on 2026-06-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_squad_assistant_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='squadplayer',
            name='fielding_position',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddConstraint(
            model_name='squadplayer',
            constraint=models.UniqueConstraint(condition=models.Q(('is_substitute', False)), fields=('squad', 'fielding_position'), name='unique_fielding_position_per_squad'),
        ),
    ]
