# Generated by Django 6.0.4 on 2026-06-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_squadplayer_fielding_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bowling_pace',
            field=models.CharField(blank=True, choices=[('fast', 'Fast'), ('medium', 'Medium'), ('spin', 'Spin')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='bowling_spin_type',
            field=models.CharField(blank=True, choices=[('leg', 'Leg Spin'), ('off', 'Off Spin'), ('both', 'Both')], max_length=10, null=True),
        ),
    ]
